//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18046
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NCrash.WinForms {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NCrash.WinForms.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Quit.
        /// </summary>
        internal static string Full_Button_Quit {
            get {
                return ResourceManager.GetString("Full_Button_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Send and Quit.
        /// </summary>
        internal static string Full_Button_SendAndQuit {
            get {
                return ResourceManager.GetString("Full_Button_SendAndQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has crashed and it will now be dismissed. If you click Quit, the application will close immediately. If you click Send and Quit, the application will close and a bug report will be send..
        /// </summary>
        internal static string Full_Message {
            get {
                return ResourceManager.GetString("Full_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Contents.
        /// </summary>
        internal static string Full_Report_Contents {
            get {
                return ResourceManager.GetString("Full_Report_Contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add a brief description of how we can reproduce the error:.
        /// </summary>
        internal static string Full_Reproduce_Exception {
            get {
                return ResourceManager.GetString("Full_Reproduce_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception.
        /// </summary>
        internal static string Full_Tab_Exception {
            get {
                return ResourceManager.GetString("Full_Tab_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Full_Tab_General {
            get {
                return ResourceManager.GetString("Full_Tab_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Error.
        /// </summary>
        internal static string Full_Window_Title {
            get {
                return ResourceManager.GetString("Full_Window_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application has crashed.
        /// A bug report has been sent to the developers. We apologize for the inconvenience. Try to continue execution?.
        /// </summary>
        internal static string MinimalWinFormsUserInterface_Message_Text {
            get {
                return ResourceManager.GetString("MinimalWinFormsUserInterface_Message_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Error.
        /// </summary>
        internal static string MinimalWinFormsUserInterface_Message_Title {
            get {
                return ResourceManager.GetString("MinimalWinFormsUserInterface_Message_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Continue.
        /// </summary>
        internal static string Normal_Button_Continue {
            get {
                return ResourceManager.GetString("Normal_Button_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &amp;Quit.
        /// </summary>
        internal static string Normal_Button_Quit {
            get {
                return ResourceManager.GetString("Normal_Button_Quit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception has occurred in your application. If you click Continue, the application will ignore this error and attempt to continue. If you click quit, the application will close immediately..
        /// </summary>
        internal static string Normal_Message {
            get {
                return ResourceManager.GetString("Normal_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Error.
        /// </summary>
        internal static string Normal_Window_Title {
            get {
                return ResourceManager.GetString("Normal_Window_Title", resourceCulture);
            }
        }
    }
}
